insert into mate_unit_value (`text`, `unitId`, `position`) VALUES
	 ('Celsius (°C)',1,0),
	 ('Fahrenheit (°F)',1,1),
	 ('Kelvin (K)',1,2),
	 ('Reaumur (°Ré)',1,3),
	 ('Newton (°N)',1,4),
	 ('Rankine (°Ra)',1,5),

	 ('Kilomètre (km)',2,0),
	 ('Hectomètre (hm)',2,1),
	 ('Décamètre (dam)',2,2),
	 ('Mètre (m)',2,3),
	 ('Décimètre (dm)',2,4),
	 ('Centimètre (cm)',2,5),
	 ('Millimètre (mm)',2,6),

	 ('Tonne (t)',3,0),
	 ('Quintal (q)',3,1),
	 ('Kilogramme (kg)',3,2),
	 ('Hectogramme (hg)',3,3),
	 ('Décagramme (dag)',3,4),
	 ('Gramme (g)',3,5),
	 ('Décigramme (dg)',3,6),
	 ('Centigramme (cg)',3,7),
	 ('Milligramme (mg)',3,8),
	 ('Micro-gramme (µg)',3,9),
	 ('Carat (carat)',3,10),
	 ('Ounce (oz)',3,11),
	 ('Pound (lb)',3,12),

	 ('Année',4,0),
	 ('Semaine',4,1),
	 ('Jour',4,2),
	 ('Heure',4,3),
	 ('Minute',4,4),
	 ('Seconde',4,5),
	 ('Milliseconde',4,6),
	 ('Microseconde',4,7),
	 ('Nanoseconde',4,8),
	 
	 ('Gigahertz (GHz)',5,0),
	 ('Megahertz (MHz)',5,1),
	 ('Kilohertz (KHz)',5,2),
	 ('Hertz (Hz)',5,3),

	 ('Kilomètre carré (km²)',6,0),
	 ('Hectomètre carré (hm²)',6,1),
	 ('Décamètre carré (dam²)',6,2),
	 ('Mètre carré (m²)',6,3),
	 ('Décimètre carré (dm²)',6,4),
	 ('Centimètre carré (cm²)',6,5),
	 ('Millimètre carré (mm²)',6,6);
